### ISSUE TITLE
Figuring out how to perform absolute temperature measurements

### ISSUE THREAD

**Issue by zougloub** [lod/seek-thermal-documentation#1]
By the way David, thanks very much for your effort to combine currently available documentation.
I was doing some updates to libseek and noticed this wiki, which is a nice way to contribute without being tied to an actual implementation.

I have seen that some people were mentioning the presence of a thermal diode, that would be used to perform absolute temperature readings, but I have also seen others directly using the raw output of the camera..
I didn't really find the time (or the need...) to either find where that diode info would be located (didn't check all the "patent pixels") or perform experiments to validate the raw method.
But I'd be willing to implement the method, if someone has found one... so anyway, I'm leaving this open as an issue, which would enable people to discuss this particular subject in a thread, until a solution is found.

**Comment by lod** [comment]
Hi zougloub,

Thanks for your contributions.

The wiki is public and can be edited by anyone with a github account, so feel free to just add any additional information you come up with.

I am going to close this issue as I would prefer that discussions on topics like the thermal diode took place on the eevblog forums. I don't think we benefit from splitting the community that already exists there.
