### ISSUE TITLE
Figuring out Initial Frames and Fixed Pattern Noise Corrections

### ISSUE THREAD

**Issue by zougloub** [lod/seek-thermal-documentation#2]
The imager sends a series of initial frames:
1. ID 4 - Looks like it at least contains recorded info about dead pixels (the zero-valued pixels) and the other pixels might be indicative of (pure speculation) integration rates
   ![frame-000-raw](https://cloud.githubusercontent.com/assets/998040/10300567/3825c334-6bc6-11e5-8112-48cda8a1a61b.png)
2. ID 9 - Two gradients.. mystery
   ![frame-001-raw](https://cloud.githubusercontent.com/assets/998040/10300565/38241462-6bc6-11e5-976e-1ebc31277ccc.png)
3. ID 8 - Almost looks like a shutter frame
   ![frame-002-raw](https://cloud.githubusercontent.com/assets/998040/10300562/382128b0-6bc6-11e5-8c21-8e8741e57b9e.png)
4. ID 7 - Something rather uniform... and light
   ![frame-003-raw](https://cloud.githubusercontent.com/assets/998040/10300566/38251e16-6bc6-11e5-8106-e1ce3b513007.png)
5. ID 10 - Something rather uniform... and dark
   ![frame-004-raw](https://cloud.githubusercontent.com/assets/998040/10300563/3821df1c-6bc6-11e5-8371-af1fcc83110a.png)
6. ID 5 - Weird
   ![frame-005-raw](https://cloud.githubusercontent.com/assets/998040/10300564/3822db06-6bc6-11e5-87a0-67b492a5b5f7.png)

whose meaning and use is not exactly clear (Frame.md), but they should be here for a reason.

Then there are the frequent sequence of ID 6 / ID 1 frames, and everybody agrees that ID 1 should be used as a reference for the pixel baseline values, and its frame should be substracted from regular (ID 3) frames.

Once we perform the reference frame substraction, and perform dead pixel interpolation, we can see that there is fixed pattern noise, with some pixels integrating faster than others.

There is that 207th column which provides information used to correct for horizontal bands, how it does that is a bit of magic at the moment.

We can see that images exhibit more than just these horizontal bands, but how would we correct for them (except from performing median/bilateral/fancier filtering, which are just lesser solutions if a clean one exists)...

**Comment by lod** [comment]
Thanks for the images, I have incorporated them into the wiki
