### ISSUE TITLE
BPC - Less basic bad pixels correction available in libseek

### ISSUE THREAD

**Issue by zougloub** [lod/seek-thermal-documentation#3]
Hi,

I just wanted to share that I have set up a pretty flexible bad pixels calibration & correction method in libseek.
Since the Seek imager has some pretty big clusters of bad pixels, just correcting for single bad pixels and interpolating the hexagon pattern is not enough, and performing median filtering for correcting bad pixels is a bit of a hack.

I came up with something I believe to be not so ugly:
- a functional (but pretty long) calibration step which identifies a contour of good pixels around a bad pixel cluster; the code is basic but the principle is to go in all directions and find the closest good pixel and to keep the list of closest good pixels
- a very basic way of interpolating value of bad pixels, which is a simple weighted sum of inverse distance to contour points... could be better of course!
- a structure used to store the bad pixels information, under the form of
  - number of + list of weights
  - number of + list of contour patterns (each contour is a list of relative pixel positions and pointer to weight index)
  - number of + list of bad pixels (each bad pixel has its position and contour pattern index)
  
  The structure is stored in ASCII format, can be written and parsed easily.
- a short implementation of correction in libseek, that uses the same in-memory structure (because speed is not exactly a constraint for this detector size)

I'm pretty sure this could be useful to other implementations, and I'm very open to comments, suggestions, fixes, whatever!

**Comment by lod** [comment]
Thanks, I linked to your algorithm from the wiki page
