### ISSUE TITLE
Seek Thermal SDK for iOS

### ISSUE THREAD

**Issue by frogg** [lod/seek-thermal-documentation#4]
Hey! Are you aware of something similar for iOS?
I've been in contact with the Thermal support but they are not helpful at all and have no idea what an SDK is. Their technical support is referring me to their sales team…

**Comment by lod** [comment]
No, I expect the protocol is basically the same with some kind of wrapper to convert the lightning traffic to serial. That is all they are doing with the USB.

I have no idea how you would get access to that serial stream, I have almost no iOS experience, happy to take a pull request if you figure it out though.
